AWS_DBT_Snowflake_Project:
  outputs:
    dev:
      account: VUZPJDO-YQC92091
      database: AIRBNB
      password : **************
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: AMYUKTHA
      warehouse: COMPUTE_WH
  target: dev
